docker run --detach \
    --hostname gitlab.example.com \
    --publish 443:443 --publish 80:80 --publish 2222:22 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:latest



    docker run -it \
        --hostname gitlab.example.com \
        --publish 443:443 --publish 80:80 --publish 2222:22 \
        --name gitlab2v \
        --restart always \
        --volume /srv/gitlab/config:/etc/gitlab \
        --volume /srv/gitlab/logs:/var/log/gitlab \
        --volume /srv/gitlab/data:/var/opt/gitlab \
        gitlab/gitlab-ce:latest




            docker run -it \
                --hostname gitlab.example.com \
                --publish 443:443 --publish 80:80 --publish 2222:22 \
                --name gitlab \
                --restart always \
                --volume /srv/gitlab/config:/etc/gitlab \
                --volume /srv/gitlab/logs:/var/log/gitlab \
                --volume /srv/gitlab/data:/var/opt/gitlab \
                gitlab/gitlab-ce:latest


r docker host to host all your Tools (jenkins, gitlab)


    docker run -it \
        --hostname gitlab.example.com \
        --publish 443:443 --publish 80:80 --publish 2222:22 \
        --name gitlab2v \
        --restart always \
        --volume /Users/hemakuma/training/gitlab/config:/etc/gitlab \
        --volume /Users/hemakuma/training/gitlab/logs:/var/log/gitlab \
        --volume /Users/hemakuma/training/gitlab/data:/var/opt/gitlab \
        gitlab/gitlab-ce:latest

/Users/hemakuma/training/gitlab/


docker run --detach \
    --hostname gitlabv3.example.com \
    --publish 4443:443 --publish 8880:80 --publish 2222:22 \
    --name gitlab3v \
    --restart always \
    --volume /Users/hemakuma/training/gitlab/:/etc/gitlab \
    --volume /Users/hemakuma/training/gitlab/:/var/log/gitlab \
    --volume /Users/hemakuma/training/gitlab/:/var/opt/gitlab \
    gitlab/gitlab-ce:latest
