---
- name: ping testing
  hosts: n9k-1
  connection: local
  gather_facts: no
  tasks:
    - name: obtain login credentials
      include_vars: credentials.yml

    - name: run show verion on remote devices
      nxos_command:
        commands:
          - show version | json
        provider: "{{ creds }}"
      register: version
    - debug: var=version.stdout_lines
