---
- name: ping testing
  hosts: n9k-1
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: admin
      password: cisco123
      transport: cli
  tasks:
    - name: run show verion on remote devices
      nxos_command:
        commands:
          - show version | json
        provider: "{{ cli }}"
      register: version
    - debug: var=version.stdout_lines
    
