---
- name: ping testing
  hosts: leafs
  connection: local
  gather_facts: no
  environment:
    - ANSIBLE_NET_USERNAME: admin
    - ANSIBLE_NET_PASSWORD: cisco123
    # test reachability to 8.8.8.8 using mgmt vrf
  tasks:
    - name: ping host
      nxos_ping: dest=8.8.8.8 vrf=management host={{ inventory_hostname }}

    # Test reachability to a few different public IPs using mgmt vrf
    # if device has name lookups turned on, you can use names
    - nxos_ping: dest={{ item }} vrf=management username=admin password=cisco123 host={{ inventory_hostname }}
      with_items:
        - 8.8.8.8
        - 4.4.4.4
        - 198.6.1.4
