---
- name: configure radius server
  hosts: n9k-1
  connection: local
  gather_facts: no
  tasks:
    - name: obtain login credentials
      include_vars: credentials.yml

    - nxos_config:
        lines:
          - server 10.230.86.165
          - server 152.69.76.90
          - use-vrf management
          - source-interface mgmt0
        parents: aaa group server radius pdit_radius
        before: aaa group server radius pdit_radius
        provider: "{{ creds }}"

#store the variable in hosts_vars
